name: giantt
description: Gantt chart app powered by Soradyne

dependencies:
  flutter:
    sdk: flutter
  soradyne_flutter:
    path: ../../packages/soradyne_flutter
  ai_chat_flutter:
    path: ../../packages/ai_chat_flutter
  # Gantt-specific dependencies
  gantt_chart: ^0.2.0
  timeline_tile: ^2.0.0
